/* SPDX-License-Identifier: GPL-2.0-or-later */

#pragma once

#define VIAL_KEYBOARD_UID {0x6E, 0x0B, 0x53, 0x62, 0x5C, 0xA3, 0xA5, 0x90}

#define VIAL_UNLOCK_COMBO_ROWS { 0, 3 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 13 }

#define RGB_MATRIX_HUE_STEP 16
#define EECONFIG_CAPS_HUE (EECONFIG_USER + 0)
#define EECONFIG_NUM_HUE (EECONFIG_USER + 1)
#define EECONFIG_COMB_HUE (EECONFIG_USER + 2)
#define EECONFIG_CAPS_SAT (EECONFIG_USER + 3)
#define EECONFIG_NUM_SAT (EECONFIG_USER + 4)
#define EECONFIG_COMB_SAT (EECONFIG_USER + 5)
